version: "3.9"
services:
  app:
    build: .
    env_file: .env
    volumes:
      - .:/app
    depends_on:
      - db
    command: python app/main.py

  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
